modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="mcse"
version="1.0.0"
displayName="Minecraft Science"
logoFile="MCSE.png"
credits="gengyoubo（耿悠博）"
authors="gengyoubo（耿悠博）"
issueTrackerURL = "https://github.com/gengyoubo/MCSE/issues" #optional
description='''
Minecraft Science module is divided into four parts: Physics, Chemistry, Biology, and Geology.
'''
displayURL = "https://github.com/gengyoubo/MCSE"
[[dependencies.mcse]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"